### ISSUE TITLE
how  to download dataset : 8thGr-NDMC-Train.csv?

### ISSUE THREAD

**Issue by ynuwm** [sujitpal/dl-models-for-qa#2]
thank you~

**Comment by sujitpal** [comment]
Look here - https://github.com/sujitpal/dl-models-for-qa#data

The original data is no longer available. Allen AI has an alternative dataset (slightly smaller and differently formatted). I had signed up to the original competition but never had the time to submit solutions, but I had the data on disk. When I started the project, I decided to reuse the data I had already, so my preprocessing code is kind of tied to that format. That data is no longer available. But the alternative dataset from AllenAI should be usable after minor changes to the preprocessing code.

**Comment by ynuwm** [comment]
Got it. I download the data from this site - https://www.kaggle.com/allenai/ai2-science-questions
Thank you anyway. @sujitpal
